apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejshello
spec:
  selector: 
   matchLabels:
     app: nodejshello
  replicas: 7
  template:
    metadata:
      labels:
        app: nodejshello
    spec:
      containers:
      - name: nodejshello
        image: huseyinbabal/node-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 400m
            memory: 32Mi
      priorityClassName: nodejspriority