apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejsmemory
spec:
  maxReplicas: 10
  minReplicas: 7
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nodejshello
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
          type: Utilization
          averageUtilization: 60