apiVersion: v1
kind: Service
metadata:
  name: nodejshelloservice
  labels:
    app: nodejshello
spec:
  selector:
    app: nodejshello
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
